export const mockupProducts = [
    {
        id: 1,
        image: "assets/images/prod/1.webp",
        category: "NOTIȚE",
        name: "Marcaje multicolore p/t file de document",
        price: "12.00",
    },
    {
        id: 2,
        image: "assets/images/prod/3.webp",
        category: "CALIGRAFIE",
        name: "Corector bandă ”Frost White” 4M",
        price: "15.00",
    },

    {
        id: 3,
        image: "assets/images/prod/4.webp",
        category: "ACCESORII",
        name: "Husă impermeabilă pentru laptop A4",
        price: "160.00",
    },
    {
        id: 4,
        image: "assets/images/prod/5.jpg",
        category: "PAPETĂRIE",
        name: "Notebook din hârtie reciclată, negru, A5",
        price: "47.00",
    },
    {
        id: 5,
        image: "assets/images/prod/2.webp",
        category: "PAPETĂRIE",
        name: "Notițe auto-adezive, hârtie Kraft, Multicolor",
        price: "13.00",
    },
    {
        id: 6,
        image: "assets/images/prod/6.jpg",
        category: "PAPETĂRIE",
        name: "Notebook inel dublu și grilă punctată, A6",
        price: "65.00",
    },
    {
        id: 7,
        image: "assets/images/prod/7.webp",
        category: "ACCESORII",
        name: "Agrafe de hârtie, 70buc, Aluminiu",
        price: "12.00",
    },
    {
        id: 8,
        image: "assets/images/prod/8.webp",
        category: "CALIGRAFIE",
        name: "Peniță pentru caligrafie, 0.5mm, Negru",
        price: "23.00",
    },
    {
        id: 9,
        image: "assets/images/prod/9.webp",
        category: "CALIGRAFIE",
        name: "Peniță pentru caligrafie, 0.6mm, Albastru",
        price: "23.00",
    },
    {
        id: 10,
        image: "assets/images/prod/10.jpg",
        category: "CALIGRAFIE",
        name: "Peniță pentru caligrafie, 0.6mm, Albastru",
        price: "23.00",
    },
    {
        id: 11,
        image: "assets/images/prod/11.jpg",
        category: "ACCESORII",
        name: "Husă pentru rechizite, plasă Nylon, cilindrică",
        price: "92.00",
    },
    {
        id: 12,
        image: "assets/images/prod/12.webp",
        category: "ACCESORII",
        name: "Husă pentru rechizite din poliester - 24cm",
        price: "15.00",
    },
    {
        id: 13,
        image: "assets/images/prod/13.webp",
        category: "CALIGRAFIE",
        name: "Pix roller XTRA 805, 0.5 mm, verde",
        price: "50.00",
    },
    {
        id: 14,
        image: "assets/images/prod/15.webp",
        category: "ACCESORII",
        name: "Foarfecă BUROMAX 163 mm, negru",
        price: "15.00",
    },
    {
        id: 15,
        image: "assets/images/prod/14.jpg",
        category: "ACCESORII",
        name: "Capsator din oțel + 300buc capse CADOU",
        price: "46.00",
    } 
];